$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: blue-demo-deployment
model:
    name: aml:iris_model
code_configuration:
  code: ./score
  scoring_script: score.py
environment: 
  conda_file: environment.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20210727.v1
instance_type: Standard_DS2_v2
instance_count: 1